"""CLI driver for the pool sensitivity grid + empirical gold (spec section 8).

Runs the KEEP/COLLAPSE/NO_CONSENSUS classification for all 36 families under
all 4 fixed pools (pool_core3/econ/bwl/all5), plus empirical gold + design-
gold shift detection based on pool_core3 alone.

Usage:
    python -m src.pool_sensitivity \\
        --reconstructed data/reconstructed_5ann.json \\
        --output-dir pool_sensitivity_output
"""

import argparse
import json
import os
from collections import Counter

from .classify import classify_family
from .gold import empirical_gold_row, shifted_row
from .majority import condition_majority
from .pools import CONDITIONS, POOLS
from .report import (
    write_collapse_breakdown,
    write_core3_keep_dropouts,
    write_empirical_gold_core3,
    write_gold_shifted_families,
    write_pool_sensitivity_grid,
)

_NON_CORE3_POOLS = [p for p in POOLS if p != "core3"]

_README = """\
# Pool sensitivity grid + empirical gold -- output guide

Generated by `python -m src.pool_sensitivity`, per
`pool_sensitivity_spec_for_claude_code.md`. Dataset-level, descriptive
analysis: no family is auto-excluded here, no model is run, no significance
testing. KEEP/EXCLUDE is a human decision made by reading these tables.

## Files

- `pool_sensitivity_grid.csv` -- one row per family (36 rows). Each pool's
  class -- KEEP / COLLAPSE / NO_CONSENSUS / EXCLUDE_BROKEN -- plus
  `stable_keep_all_pools` (True only when all four pools independently land
  on KEEP) and `family_gold_shifted` (True if pool_core3's empirical gold
  moved off design gold on any condition -- see gold_shifted_families.csv).
  `core3_class_detail` shows pool_core3's actual majority label per
  condition for a quick look without opening empirical_gold_core3.csv.
  **EXCLUDE_BROKEN is checked before everything else**, including
  NO_CONSENSUS: any condition whose majority landed on the DISTRACTOR role
  marks the whole family broken for that pool, regardless of what the other
  two conditions look like or whether they even have a majority.
- `collapse_breakdown.csv` -- one row per (family, pool) that came out
  COLLAPSE. Distractor-caused breakage is no longer a COLLAPSE subtype (it's
  its own EXCLUDE_BROKEN class now, not listed here) -- every row in this
  file is `collapse_type=structural`: no distractor majority anywhere, but
  two or more conditions converged onto the same label (e.g. +ba and +ma
  both read as TENTATIVE). Rows record exactly which conditions collapsed
  together (`collapse_pair`, e.g. "ba=ma") and onto which label
  (`collapse_label`).
- `core3_keep_dropouts.csv` -- families that are KEEP under pool_core3 but
  not `stable_keep_all_pools` (i.e. at least one of pool_econ/bwl/all5
  disagrees). Shows each pool's class and `dropped_by_pools`: which of
  econ/bwl/all5 pulled the family off KEEP. Use this to see whether it's
  consistently the same pool doing the dropping (e.g. always pool_econ)
  before reading anything into it -- see the caveat below.
- `empirical_gold_core3.csv` -- one row per (family, condition) (108 rows),
  pool_core3 only. `majority_label` is the empirical gold when
  `has_majority` is True (None otherwise); compared against
  `design_gold_label` to set `gold_shifted`. `margin` (top count minus
  runner-up count) says how solid that majority is.
- `gold_shifted_families.csv` -- just the `gold_shifted=True` rows from
  above, projected to `empirical_gold_label` instead of `majority_label`.
  **These are not failed families** -- they're families where the
  annotators' actual majority reading differs from what was designed. They
  default to staying in the main set with gold taken from the empirical
  value; a low `margin` is the one reason to look twice at how stable that
  empirical value is.

## Two things this analysis explicitly does NOT support

- **Comparing KEEP counts across pools as a quality signal.** pool_econ,
  pool_bwl, and pool_all5 all include a 4th (or 5th) voter beyond the
  mutually-high-agreement core3, so their classifications can differ from
  core3's for purely mechanical reasons -- an even-sized pool produces more
  ties, and Econ/BWL's own divergence pulls some families off KEEP. A lower
  KEEP count under pool_bwl than under pool_core3 is not evidence the
  stimuli got worse; it's an artifact of pool composition. The grid's actual
  use is finding the `stable_keep_all_pools=True` intersection, not ranking
  pools against each other.
- **Treating BWL as a validated annotator.** BWL appears only in pool_bwl
  and pool_all5, and only as a stress test -- checking whether this
  annotator, independent of the response-process concerns raised elsewhere
  (see diagnostic_output/), would overturn core3's classification if
  included. Appearing in these pools is not an endorsement of BWL's labels.
"""


def _group_by_family(items: list[dict]) -> dict[str, dict[str, dict]]:
    families: dict[str, dict[str, dict]] = {}
    for item in items:
        families.setdefault(item["family_id"], {})[item["particle_condition"]] = item
    return families


def _core3_detail(condition_results: dict[str, dict]) -> str:
    parts = [f"{c}:{condition_results[c]['majority_label'] or 'NONE'}" for c in CONDITIONS]
    return "; ".join(parts)


def run_all(items: list[dict], output_dir: str) -> None:
    os.makedirs(output_dir, exist_ok=True)
    families = _group_by_family(items)

    grid_rows = []
    collapse_rows = []
    gold_rows = []
    dropout_rows = []

    for family_id in sorted(families):
        fam_items = families[family_id]

        classifications = {}
        for pool_name, pool_members in POOLS.items():
            condition_results = {c: condition_majority(fam_items[c], pool_members) for c in CONDITIONS}
            classification = classify_family(condition_results)
            classifications[pool_name] = classification
            if classification["class"] == "COLLAPSE":
                collapse_rows.append(
                    {
                        "family_id": family_id,
                        "pool": pool_name,
                        "collapse_type": classification["collapse_type"],
                        "collapse_pair": classification["collapse_pair"],
                        "collapse_label": classification["collapse_label"],
                    }
                )
            if pool_name == "core3":
                core3_condition_results = condition_results

        family_gold_rows = [empirical_gold_row(fam_items[c]) for c in CONDITIONS]
        gold_rows.extend(family_gold_rows)
        family_gold_shifted = any(r["gold_shifted"] for r in family_gold_rows)

        stable_keep = all(classifications[pool]["class"] == "KEEP" for pool in POOLS)
        grid_rows.append(
            {
                "family_id": family_id,
                "core3_class": classifications["core3"]["class"],
                "econ_class": classifications["econ"]["class"],
                "bwl_class": classifications["bwl"]["class"],
                "all5_class": classifications["all5"]["class"],
                "stable_keep_all_pools": stable_keep,
                "family_gold_shifted": family_gold_shifted,
                "core3_class_detail": _core3_detail(core3_condition_results),
            }
        )

        if classifications["core3"]["class"] == "KEEP" and not stable_keep:
            dropped_by = [p for p in _NON_CORE3_POOLS if classifications[p]["class"] != "KEEP"]
            dropout_rows.append(
                {
                    "family_id": family_id,
                    "core3_class": classifications["core3"]["class"],
                    "econ_class": classifications["econ"]["class"],
                    "bwl_class": classifications["bwl"]["class"],
                    "all5_class": classifications["all5"]["class"],
                    "dropped_by_pools": ",".join(dropped_by),
                }
            )

    shifted_rows = [shifted_row(r) for r in gold_rows if r["gold_shifted"]]

    write_pool_sensitivity_grid(grid_rows, os.path.join(output_dir, "pool_sensitivity_grid.csv"))
    write_collapse_breakdown(collapse_rows, os.path.join(output_dir, "collapse_breakdown.csv"))
    write_empirical_gold_core3(gold_rows, os.path.join(output_dir, "empirical_gold_core3.csv"))
    write_gold_shifted_families(shifted_rows, os.path.join(output_dir, "gold_shifted_families.csv"))
    write_core3_keep_dropouts(dropout_rows, os.path.join(output_dir, "core3_keep_dropouts.csv"))
    with open(os.path.join(output_dir, "Pool_Sensitivity_README.md"), "w", encoding="utf-8") as f:
        f.write(_README)

    for pool_col in ("core3_class", "econ_class", "bwl_class", "all5_class"):
        counts = Counter(row[pool_col] for row in grid_rows)
        print(f"  {pool_col}: {dict(counts)}")
    print(f"  stable_keep_all_pools=True: {sum(1 for r in grid_rows if r['stable_keep_all_pools'])}")
    print(f"  family_gold_shifted=True: {sum(1 for r in grid_rows if r['family_gold_shifted'])}")
    print(f"  core3 KEEP but dropped elsewhere: {len(dropout_rows)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Pool sensitivity grid + empirical gold (4 pools, 36 families).")
    parser.add_argument("--reconstructed", required=True, help="Path to module 1's reconstructed items JSON.")
    parser.add_argument("--output-dir", required=True, help="Directory to write all output files into.")
    args = parser.parse_args()

    with open(args.reconstructed, encoding="utf-8") as f:
        items = json.load(f)

    run_all(items, args.output_dir)
    print(f"Pool sensitivity analysis complete: {len(items) // 3} families written to {args.output_dir}")


if __name__ == "__main__":
    main()
