"""CLI driver for the annotator condition-wise diagnostic (spec section 8).

Runs all 4 targets (Econ/Media/Materials/EngLit) x 2 no-option modes (A/B) =
8 combinations. BWL never appears as a target or in any reference_pool (spec
section 2): its response-process concerns can't be diagnosed via agreement
with others, and including it would pollute the pool used to diagnose Econ.

Usage:
    python -m src.diagnostic \\
        --reconstructed data/reconstructed_5ann.json \\
        --output-dir diagnostic_output
"""

import argparse
import json
import os

from .core import run_diagnostic
from .metrics import condition_summary, confusion_matrices, disagreement_directions, reference_marginals
from .plots import plot_confusion_heatmap
from .report import (
    write_condition_summary,
    write_confusion_variant,
    write_cross_annotator_summary,
    write_disagreement_directions,
    write_item_level,
    write_reference_marginals,
)

TARGETS = ["Econ", "Media", "Materials", "EngLit"]
MODES = ["A", "B"]

_README = """\
# Annotator condition-wise diagnostic -- output guide

Generated by `python -m src.diagnostic`, per `Econ_diagnostic_spec_for_claude_code.md`.
Descriptive QC only: nothing here excludes an annotator, decides family
inclusion, or runs significance tests.

## Files

- `diagnostic_summary_all_annotators.csv` -- the one table to look at first.
  Four annotators x two no-option modes, each with coverage/agreement for
  bare/ba/ma/overall. Answers: is any one annotator's low agreement confined
  to a single condition, or is it diffuse?
- `{ann}_condition_summary_{mode}.csv` -- that annotator's row above, unpacked
  (adds raw counts alongside the rates).
- `{ann}_reference_marginals_{mode}.csv` -- where the reference pool's
  majority vote landed, per condition. Check this before reading anything
  into a "dominant disagreement direction": if a condition's reference labels
  are almost all one category, a concentrated-looking direction can be
  structurally forced rather than a real pattern.
- `{ann}_confusion_{condition}_{counts,rownorm}_{mode}.csv` -- rows =
  reference-pool majority label, columns = target's answer. counts and
  row-normalized versions both given (counts matter more at this sample size).
- `{ann}_disagreement_directions_{mode}.csv` -- every off-diagonal cell with
  two differently-denominated rates (share of all disagreements in that
  condition vs. rate within that reference label), plus a `low_n` flag for
  any cell under 8 -- those are reported as numbers only, not interpreted.
- `{ann}_item_level_{mode}.csv` -- one row per item: every reference member's
  answer, the target's answer, agreement, naturalness/hesitation, so a
  dominant confusion cell can be traced back to specific items.
- `{ann}_confusion_{condition}_{mode}.png` -- heatmap of the counts version.

## Known asymmetry (do not "correct" it -- just keep it in mind)

When Econ is the target, the reference pool is Media+Materials+EngLit --
the mutually-high-agreement core-3. When any of those three is the target,
their reference pool includes Econ, whose divergence is exactly what
prompted this diagnostic. So non-Econ targets face a noisier reference pool
and their agreement numbers are pulled down by that noise. This asymmetry
favors Econ (its own comparison is against the cleanest possible reference).
If Econ still comes out lower on some condition despite that head start,
the finding is more robust for it, not less.

## Primary vs. robustness mode

Mode A (a reference-pool member who checked "no valid option" but still gave
an answer is counted at that answer) is the primary result, fixed before
looking at any numbers. Mode B (same annotator instead treated as an
abstention) is the robustness check. If A and B tell the same condition-wise
story, the no-option handling isn't driving the conclusion.
"""


def _target_reference_pool(target: str) -> list[str]:
    return [t for t in TARGETS if t != target]


def _pick(rows: list[dict], condition: str) -> dict:
    return next(r for r in rows if r["condition"] == condition)


def run_all(items: list[dict], output_dir: str) -> None:
    os.makedirs(output_dir, exist_ok=True)
    summary_rows = []

    for target in TARGETS:
        reference_pool = _target_reference_pool(target)
        ann = target.lower()

        for mode in MODES:
            records = run_diagnostic(items, target, reference_pool, mode)

            cond_summary = condition_summary(records)
            write_condition_summary(cond_summary, os.path.join(output_dir, f"{ann}_condition_summary_{mode}.csv"))

            marginals = reference_marginals(records)
            write_reference_marginals(marginals, os.path.join(output_dir, f"{ann}_reference_marginals_{mode}.csv"))

            write_item_level(records, reference_pool, os.path.join(output_dir, f"{ann}_item_level_{mode}.csv"))

            directions = disagreement_directions(records)
            write_disagreement_directions(
                directions, os.path.join(output_dir, f"{ann}_disagreement_directions_{mode}.csv")
            )

            matrices = confusion_matrices(records)
            write_confusion_variant(
                matrices, "raw",
                lambda condition: os.path.join(output_dir, f"{ann}_confusion_{condition}_counts_{mode}.csv"),
            )
            write_confusion_variant(
                matrices, "rownorm",
                lambda condition: os.path.join(output_dir, f"{ann}_confusion_{condition}_rownorm_{mode}.csv"),
            )
            for condition in ("bare", "ba", "ma", "overall"):
                plot_confusion_heatmap(
                    matrices[condition]["raw"],
                    f"{target} vs. reference pool -- {condition} (mode {mode})",
                    os.path.join(output_dir, f"{ann}_confusion_{condition}_{mode}.png"),
                )

            bare, ba, ma, overall = (_pick(cond_summary, c) for c in ("bare", "ba", "ma", "overall"))
            summary_rows.append(
                {
                    "annotator": target,
                    "mode": mode,
                    "bare_cov": bare["coverage"],
                    "bare_agr": bare["agreement_rate"],
                    "ba_cov": ba["coverage"],
                    "ba_agr": ba["agreement_rate"],
                    "ma_cov": ma["coverage"],
                    "ma_agr": ma["agreement_rate"],
                    "overall_cov": overall["coverage"],
                    "overall_agr": overall["agreement_rate"],
                }
            )

    write_cross_annotator_summary(summary_rows, os.path.join(output_dir, "diagnostic_summary_all_annotators.csv"))
    with open(os.path.join(output_dir, "README.md"), "w", encoding="utf-8") as f:
        f.write(_README)


def main() -> None:
    parser = argparse.ArgumentParser(description="Annotator condition-wise diagnostic (leave-one-out, bare/ba/ma).")
    parser.add_argument("--reconstructed", required=True, help="Path to module 1's reconstructed items JSON.")
    parser.add_argument("--output-dir", required=True, help="Directory to write all diagnostic output files into.")
    args = parser.parse_args()

    with open(args.reconstructed, encoding="utf-8") as f:
        items = json.load(f)

    run_all(items, args.output_dir)
    print(f"Diagnostic complete: {len(TARGETS)} targets x {len(MODES)} modes written to {args.output_dir}")


if __name__ == "__main__":
    main()
